@baseUrl = http://localhost:3000/api
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkY2ZlYjQ1OS1mN2Q5LTQ4MDctYmNhMS1mYzBmOWNjMmYwMmUiLCJlbWFpbCI6ImFsaWNlQGV4YW1wbGUuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzcyODA5OTU0LCJleHAiOjE3NzI4OTYzNTR9.oJr0L_Klir3kLKLaVO7qEnFwrz-i15OjDUhxAl6Hvos
@viewerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTFiYTY1Ny1lYjhhLTQ2M2UtODM1MS01NGM1OTg3NDFhYTEiLCJlbWFpbCI6ImNoYXJsaWVAZXhhbXBsZS5jb20iLCJyb2xlIjoidmlld2VyIiwiaWF0IjoxNzcyODA5Mjc3LCJleHAiOjE3NzI4OTU2Nzd9.Mrunl-QU-JaGE5t4rHWudrp09_Gbqdfm00e2x_NmS4E
@bobToken = REMPLACER_TOKEN_BOB_MEMBER

### Login Alice (admin)
POST {{baseUrl}}/auth/login
Content-Type: application/json

{ "email": "alice@example.com", "password": "password123" }

### Login Charlie (viewer)
POST {{baseUrl}}/auth/login
Content-Type: application/json

{ "email": "charlie@example.com", "password": "password123" }

### ADMIN peut supprimer → 204
DELETE {{baseUrl}}/users/USER_UUID
Authorization: Bearer {{adminToken}}

### VIEWER ne peut pas supprimer → 403
DELETE {{baseUrl}}/users/USER_UUID
Authorization: Bearer {{viewerToken}}

### MEMBER peut modifier son propre profil → 200
PATCH {{baseUrl}}/users/BOB_UUID
Authorization: Bearer {{bobToken}}
Content-Type: application/json

{ "name": "Bob Martin-Dupont" }

### MEMBER ne peut PAS modifier le profil d'Alice → 403
PATCH {{baseUrl}}/users/ALICE_UUID
Authorization: Bearer {{bobToken}}
Content-Type: application/json

{ "name": "Alice Hacké" }